### ISSUE TITLE
Loading spacy data fails

### ISSUE THREAD

**Issue by mouadino** [RasaHQ/rasa_nlu#996]
**Rasa NLU version** (e.g. `0.7.3`):
11.0.4

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
`spacy_sklearn` with `spacy_model_name` set to `en_core_web_md`.

**Operating system** (windows, osx, ...):
osx

**Issue**:
Hey there I am using Pipenv to install spacy language like so:

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
rasa = "*"
rasa_core = "*"
sklearn_crfsuite = "*"
spacy = "*" 
Flask = "*"
gunicorn = "*"
en = {file = "https://github.com/explosion/spacy-models/releases/download/en_core_web_md-1.2.0/en_core_web_md-1.2.0.tar.gz"}

[dev-packages]
chatbot = {path = ".", editable = true}
pytest = "*"

[requires]
python_version = "3.6"
```

and then to avoid using spacy link command I am telling rasa to load the module with its original name with the following config:

```
{
  "pipeline": "spacy_sklearn",
	"spacy_model_name": "en_core_web_md",
  "path" : "./resources/models/nlu",
  "data" : "./resources/data/nlu.md"
}
```

But when I run the training it fails with:

```
 ensure_proper_language_model
    "Make sure you have downloaded the correct model (https://spacy.io/docs/usage/).")
Exception: Failed to load spacy language model for lang 'en'. Make sure you have downloaded the correct model (https://spacy.io/docs/usage/).
```

And by looking at the code, the comment says that its a failure when language is not loaded from file system but it is (https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/utils/spacy_utils.py#L128).

Can someone help?

**Comment by mouadino** [comment]
BTW our code is open source in case you need to reproduce it check https://github.com/ThoughtWorksInc/twde-chatbot/pull/3, thank you.

**Comment by akelad** [comment]
can you post the error it throws? Also, in the config file of the PR you linked, you're still specifying the path and data - this is no longer supported. You need to specify it as an argument in the train command: https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/train.py#L27

**Comment by meandor** [comment]
[OKAY] Loaded ENV .env File as KEY=VALUE Format
14:52:52 web.1   |  INFO:apscheduler.scheduler:Scheduler started
14:52:52 web.1   |  Traceback (most recent call last):
14:52:52 web.1   |    File "/python3.6/site-packages/rasa_nlu/config.py", line 79, in __init__
14:52:52 web.1   |      file_config = simplejson.loads(f.read())
14:52:52 web.1   |    File "/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
14:52:52 web.1   |      return _default_decoder.decode(s)
14:52:52 web.1   |    File "/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
14:52:52 web.1   |      obj, end = self.raw_decode(s)
14:52:52 web.1   |    File "/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
14:52:52 web.1   |      return self.scan_once(s, idx=_w(s, idx).end())
14:52:52 web.1   |  simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
14:52:52 web.1   |  During handling of the above exception, another exception occurred:
14:52:52 web.1   |  Traceback (most recent call last):
14:52:52 web.1   |    File "./chatbot/cli/train.py", line 11, in <module>
14:52:52 web.1   |      run()
14:52:52 web.1   |    File "./chatbot/cli/train.py", line 6, in run
14:52:52 web.1   |      intent_classificator.train_classificator()
14:52:52 web.1   |    File "src/chatbot/chatbot/nlu/intent_classificator.py", line 15, in train_classificator
14:52:52 web.1   |      trainer = Trainer(RasaNLUConfig(conf.get_value('nlu-config-file-path')))
14:52:52 web.1   |    File "/python3.6/site-packages/rasa_nlu/config.py", line 81, in __init__
14:52:52 web.1   |      raise InvalidConfigError("Failed to read configuration file '{}'. Error: {}".format(filename, e))
14:52:52 web.1   |  rasa_nlu.config.InvalidConfigError: Failed to read configuration file 'resources/nlu_model_config.yml'. Error: Expecting value: line 1 column 1 (char 0)
14:52:52 web.1   Exited with exit code 1

**Comment by tmbo** [comment]
@meandor you are trying to load a yml config file (version 0.12) with your rasa nlu installation that seems to be `0.11.x`

**Comment by meandor** [comment]
@tmbo no i updated to rasa_nlu 0.12

**Comment by mouadino** [comment]
I think what @meandor is saying is that rasa-core that is PyPI  0.8.5 depends on rasa-nlu without pinning so it gets the last one that was released today or yesterday i.e. 0.12.0 but this later broke the API and doesn't work with rasa-core 0.8.5, I guess you're trying to upload the new rasa-core to PyPI that should work with the new rasa-nlu but keep in mind that it 0.8.5 that is in PyPI is still broken.

**Comment by tmbo** [comment]
@mouadino there is a version building (takes a while, 0.8.6) that will pin the NLU version to be < 0.12

We do use semantic versioning, but since we still need to iterate fast, breaking chhanges are introduced in minor version changes, *which is expected and correct* as long as the major version is `0`. We are trying to move towards, 1.0 but need to change a couple things to get there.

The issue was, as you said, that core didn't pin the version - which is fixed now and what we will keep in the future. 

Once travis finishes building them, there will be a 
0.8.6 rasa core release that works with 0.11.x rasa NLU and a 
0.9.0a1 rasa core release that works withh 0.12.x rasa NLU

**Comment by mouadino** [comment]
@tmbo We just tried to upgrade again to latest versions of rasa first stable one with rasa_core 0.8.6 and rasa_nlu 0.11.5 then we tried with rasa_core 0.9.0a2 and rasa_nlu 0.12.2 with the configuration changes as suggested but the issue still persists, just as a reminder, we want to install spacy data using pip/pipenv and this later fails in the same place https://github.com/RasaHQ/rasa_nlu/blob/0.12.2/rasa_nlu/utils/spacy_utils.py#L144 I personally don't know what that check is for, but it seems like it's breaking the recommended way of installing spacy data and also make our flow slower since we cannot use pip cache to manage spacy data and have to redownload it each time in our CI and deployment phase :(

**Comment by tmbo** [comment]
@mouadino ok thats not what we are aiming for :D 

What's the command you are using when you install the spacy model? I'll test it locally to see if I can reproduce it. Might make sense to remove that check, might not be necessary anymore for spacy 2.0

**Comment by mouadino** [comment]
@tmbo Thanks for the quick reply, this is the changeset https://github.com/ThoughtWorksInc/twde-chatbot/pull/22 that we did that keep failing with error above.

Before we use `python -m spacy download en_core_web_md && pipenv run python -m spacy link --force en_core_web_md en` combination to manage spacy data, however with moving it to in Pipfile https://github.com/ThoughtWorksInc/twde-chatbot/pull/22/files#diff-1e61a31bf9b94805f869dc4137ec1885R21 and even with the two versions stated above it fails.

If you want to reproduce, maybe checkout our branch and then run:

```
pipenv install && pipenv run python ./chatbot/cli/train.py
```

**Comment by tmbo** [comment]
@mouadino I just took a look at the file you linked, and you shouldn't install the `1.2.0` model as it is not compatible with spacy 2.0 - rather use https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz

**Comment by tmbo** [comment]
I just tried it in my env and when I install that new model with pip and load it in spacy it has a path set. But I'll try it in a fresh env in a minute as well just to make sure it really is loading the one I installed with pip.

**Comment by mouadino** [comment]
Nice upgrade to 2.0.0 of spacy data works, thank you. 

Closing this issue.
